### ISSUE TITLE
1.3.4: Selected service other than RSS Breaks Extension and Can't Change Option.

### ISSUE THREAD

**Issue by MarkRH** [shgysk8zer0/awesome-rss#112]
**Describe the bug**
It seems once I pick something other than the default RSS for Subscribe Using it breaks the extension.  For example, I picked Feedly but when I went back to it Next-Cloud was selected and picking RSS doesn't stick.  Seems like it's not reading or saving the preferences properly.  I even tried this with a clean profile.

**To Reproduce**
1. Install Extension
2. Change Subscribe Using to Feedly for example. 
3. Go back to settings and see that it has changed and if you select "RSS" it doesn't save.

**Expected behavior**
It should remember the option I picked and save it if I change it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8035962/45925628-d2981700-bede-11e8-9ffc-711eddf3ff2f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Firefox Browser 
 - Version 62.0.2

I discovered this after trying to install it in Nightly which does not have a built in RSS ability.

**Comment by MarkRH** [comment]
Well, I installed version 1.3.0 and was able to get that one working again.  It also works in Night when picking the Feedly option, and it keeps the setting.

**Comment by Offerel** [comment]
I think the problem starts with 1.3.1 where NextCloud and TT-RSS was added to the services. When i now select for example Inoreader as a service, it defaults every time to NextCloud. But also in 1.3.0 the behavior is not what i expected. If i choose Inoreader, i can see a request to inoreader.com but afterwards the Previewpage from Firefox is opened with the RSS Feed.

This is my first time to use that plugin, since i search a way to get a rss-feed indicator when the rss functionality is completely removed from Firefox. I can live with this decision, but its not the best one. What i really need is a icon in the awesomebar, what this addon provides and then subscribe with a service like Inoreader. If this bug could be fixed, it should work as i expected it.

**Comment by happysurf** [comment]
I use the extension for discover feed links for my Netvibes pages, with RSS allowed in Subscribe Using options, nothing happen when I click on popup and then the setting back to Next Cloud Service.
This problem on Firefox 64beta3.

**Comment by KamiYamabushi** [comment]
Can confirm this functionality is still broken.

**Comment by shgysk8zer0** [comment]
Sorry for being slow to get around to this. Does anyone have any log output?

**Comment by shgysk8zer0** [comment]
1.3.5 is being reviewed and should be available soon.

**Comment by happysurf** [comment]
In 1.3.5 version, I get this message when I open a feed with **RSS setting** in Subscribe Using options:

![rss4](https://user-images.githubusercontent.com/13637587/47548238-b978f080-d8f8-11e8-949f-eba1b077cd81.png)

Is impossible for me retrieve the RSS link page in any way.

**Comment by shgysk8zer0** [comment]
@happysurf Firefox version?

I'm assuming 63+, right?

**Comment by MarkRH** [comment]
Sounds like @happysurf might be using 64Beta or Nightly which seems to have removed the ability to preview RSS feeds in the browser completely so it always throws up the open/save as dialog when the "RSS" option is chosen.  63 Release seems to still preview them.

**Comment by happysurf** [comment]
> 
> 
> @happysurf Firefox version?
> 
> I'm assuming 63+, right?

Yes, Firefox 64 beta3.
