### ISSUE TITLE
Open feeds in current tab with left-click

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/awesome-rss#30]
### Steps to reproduce
1.  Navigate to https://en.wikipedia.org/wiki/Special:RecentChanges
2.  Left-click the feed icon in the url bar

### Expected behavior
Feed page should be opened in current tab

### Actual behavior
Feed page opens in a new tab at the end

### Notes
Feed icon should also support middle-click so it can open in a new tab when it's desired

**Comment by shgysk8zer0** [comment]
I'll add a default feed preview option to control opening behavior.
Not sure which will be the default, since there's a decent case for new/current tab:
- Current tab is normally the default behavior, but would navigate away from a page you're obviously interested in enough to subscribe to. In my opinion, that would be like taking you to a user's profile on Twitter if you follow them.
- Opening in new tab, in my opinion, provides a better UX, but is not likely to be expected behavior. If not default, it can still be accomplished by middle or right click, but only if these actions are available (laptops with trackpads, mobile devies)
