### ISSUE TITLE
Doesn't show RSS channels on some pages

### ISSUE THREAD

**Issue by dos1** [shgysk8zer0/awesome-rss#50]
### Steps to reproduce
1.  Go to https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/reviews/

### Expected behavior
The Awesome RSS's button should be shown.

### Actual behavior
The built-in RSS button lights up, but Awesome RSS doesn't show up (but it works for some other pages).

**Comment by Keith94** [comment]
Firefox 57 workaround:

1. Go to about:config
2. Create new boolean `privacy.resistFingerprinting.block_mozAddonManager`
3. Set the value to `true`

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c24

**Comment by shgysk8zer0** [comment]
Thanks, @Keith94 

@dos1 Mozilla blocks content scripts on certain Mozilla sites. A bug filed reporting this issue was marked as resolved and won't fix, so this is not something that is likely to change.

I thought about adding the `privacy.resistFingerprinting.block_mozAddonManager` to the README or in the about section, but I do not want to provide assistance in working around something that is done for security.

**Comment by dos1** [comment]
So I just had a bad luck of testing the extension on AMO first. Thanks! :)
