### ISSUE TITLE
YouTube channels' RSS feeds

### ISSUE THREAD

**Issue by veloute** [shgysk8zer0/awesome-rss#51]
### Steps to reproduce
1.  Go to a person's YouTube channel

### Expected behavior
The Awesome RSS button to be in the URL bar for the channel's  RSS feed for their videos.

### Actual behavior
Awesome RSS does nothing when on the channel's page

**Comment by shgysk8zer0** [comment]
I cannot display feeds that simply do not exist. It is possible that some channels have regular links to feeds, but those would not be RSS feeds. 

As example:
[![YouTube screenshot](https://i.imgur.com/0DBEmVC.png)](https://i.imgur.com/0DBEmVC.png)

Note that Firefox's own subscribe button does not detect feeds either.

Feeds are declared and checked for using either of the following markup:
```html
<link rel="alternate" type="application/rss+xml" href="..." />
<link rel="alternate" type="application/atom+xml" href="..." />
```

**Comment by Keith94** [comment]
I like to use [RSS Box](https://rssbox.herokuapp.com/) to get feeds for YouTube channels. The feed links look like this: https://www.youtube.com/feeds/videos.xml?channel_id=UCmeds0MLhjfkjD_5acPnFlQ

**Comment by veloute** [comment]
Every channel has an RSS feed. The structure of a channel's RSS feed is: https://www.youtube.com/feeds/videos.xml?channel_id=XXXX. The channel ID is the string of text after www.youtube.com/channel/.

**Comment by shgysk8zer0** [comment]
I might create a separate add-on for that, but it is working exactly as it should. There are no feed `<link>`s on YouTube.

Looking into how to make it now. Would anyone happen to know a reliable means of getting channel id from a video? Key word there being *reliable*, since I don't want it breaking when YouTube changes something.

😲 YouTube's `<head>` is a bloated mess!

**Comment by shgysk8zer0** [comment]
Not working on it yet, but created [YouTube Subscribe Addon](https://github.com/shgysk8zer0/youtube-subscribe-addon)

**Comment by veloute** [comment]
I'm not sure myself, but it seems this userscript is able to do it on videos. Maybe take a look at this to get an idea? https://greasyfork.org/en/scripts/1760-youtube-rss-feed

**Comment by shgysk8zer0** [comment]
@veloute No use. Youtube no longer uses any of those attributes.

Attempting to filter using
```javascript
$$('a').map(a => new URL(a.href, document.URL)).filter(url => url.pathname.startsWith('/channel')).map(url => url.href)
```
which results in over 100 matches.

It did, however, show that there are/might be feeds for playlists as well.

Also tried `[data-channel-external-id]`, again with multiple results.

It is very apparent to me that Google is trying to kill RSS. And that kinda makes sense since they cannot do ads or tracking cookies in feed readers.

The good news is that it works with my feed readers, so that gives me quite a bit of extra incentive.

**Comment by shgysk8zer0** [comment]
@veloute if you're interested, I just released the YouTube version as an experimental add-on at https://addons.mozilla.org/en-US/firefox/addon/youtube-feeds/

It supports subscribing to users, channels, & playlists.
