### ISSUE TITLE
Allow to move the button

### ISSUE THREAD

**Issue by dimqua** [shgysk8zer0/awesome-rss#52]
I use "[Reload in address bar](https://addons.mozilla.org/addon/reload-in-address-bar)" addon in addition to Awesome-RSS. That's why, I would like to have a possibility to move the RSS button to the left.

Currently behavior: 
![](https://i.imgur.com/LWp8aTG.png)

This how it should be like: 
![](https://i.imgur.com/qXmv18w.png)

**Comment by shgysk8zer0** [comment]
This would be the responsibility of Firefox to allow customizing the order of icons. Personally, I do not think that add-ons should be allowed to specify their order, because who would ever pick anything other than 1 (or 0, depending on indexing)?

[1397788 - Allow reordering of icons in URL bar in Customize mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1397788) was reported to Firefox about a month ago and was marked as "wontfix", so it is doubtful that this will be changing anytime soon.

**Comment by Keith94** [comment]
You can try an unofficial [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) hack.

```css
#_e1ed7a80-7c11-4f7e-968b-79b551a0067f_-page-action {
  -moz-box-ordinal-group: 2;
}
```

![image](https://user-images.githubusercontent.com/5490615/31867183-66b14d60-b73f-11e7-828f-ee3aabb9d60a.png)

Or use a [different reload in urlbar add-on](https://addons.mozilla.org/firefox/addon/reload-in-urlbar/).
