### ISSUE TITLE
The page action icon is shown on pages without feeds

### ISSUE THREAD

**Issue by MikkCZ** [shgysk8zer0/awesome-rss#56]
### Steps to reproduce
1.  Go to https://kontext.korpus.cz/first_form (no feeds are there).
2.  See the page action icon shown but inactive (btw. hard to tell especially on dark theme).

### Expected behavior
No page action should be shown when there are no feeds (similar behaviour like when the reader mode icon is not shown, when the reader mode is not available).

### Actual behavior
The page action icon is show inactive and does nothing when clicked.

**Comment by shgysk8zer0** [comment]
You run Nightly, right?

I've experienced the issue as well, but only on Nightly. It seems that they're making some changes to page action (adding ability to move to the three dots menu), and this is causing the icon to be shown when it shouldn't.

I believe the issue with Test Pilot (#55) is closely related. I think content scripts are blocked as they often are on Mozilla pages. There's a similar issue with Page Shots, or whatever it is called now.

I think this is probably an invalid issue and should be reported to Mozilla instead.

Does that seem correct to you? If so, I'll close both issues.

**Comment by MikkCZ** [comment]
You are right, I am running Nightly. I will check with mozregression in few minutes and close this with a reference to the right bug in BMO.

**Comment by MikkCZ** [comment]
It's really intentional in [bug 1395387](https://bugzilla.mozilla.org/show_bug.cgi?id=1395387). For this extension it probably means to change the behavior, respectively update the icon color to show black in the page actions menu and in the url bar according to the theme.

**Comment by shgysk8zer0** [comment]
I tried a transparent icon instead but, in my opinion, the gap created is worse. Changing dimensions and `viewBox` has no effect on size, so that space will always be taken, to the best of my knowledge.

Using `stroke` instead of `fill` to create an outline works, but doesn't really imply "not available". Adding a crossed-though circle 🚫 would communicate this, but I don't like that option.

The opacity set on disabled icons is pretty decent. I think I might update the title as well.

Really, I think they made the wrong call making `browser.pageAction.hide` *disable* instead of *hide*.

**Comment by MikkCZ** [comment]
In my add-on i have made [this change](https://github.com/MikkCZ/pontoon-tools/commit/6ea66ef8a5e70c8f74fda93185701f55acd835bf), but there is difference in icon colors.

I think you can use opacity + update the page action title when there are no feed available.

**Comment by happysurf** [comment]
> Really, I think they made the wrong call making browser.pageAction.hide disable instead of hide.

This is a very bad story, is not possible contact the Mozilla developers?

**Comment by MikkCZ** [comment]
The change has been made in https://bugzilla.mozilla.org/show_bug.cgi?id=1395387, the right people are probably there.

As for how it behaves in Photon, the color depends on the place where the icon is. In the menu the in/active color should be grey/black. In the addressbar it varies based on the theme too.

**Comment by Keith94** [comment]
I use this code in [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) to hide the icon when it's disabled

```css
#pageAction-urlbar-_97d566da-42c5-4ef4-a03b-5a2e5f7cbcb2_[disabled="true"] {
  display: none;
}
```

**Comment by shgysk8zer0** [comment]
I went with opacity for the icon. Using a black icon really isn't a good solution for light themes where it will draw even more attention to it.

In order to handle the issue on Mozilla pages where content scripts are never run, I set the icon and title to disabled by default and then update if feeds are found.

A bit off topic, but what Mozilla does blocking add-ons on certain sites has me considering if it would be beneficial to add this ability into Content-Security-Policy. It sounds like a good idea at first, but I'm sure it would be used to disable ad blockers and would be problematic with password managers.

**Comment by happysurf** [comment]
> A  bit off topic, but what Mozilla does blocking add-ons on certain sites  has me considering if it would be beneficial to add this ability into  Content-Security-Policy. It sounds like a good idea at first, but I'm  sure it would be used to disable ad blockers and would be problematic  with password managers.

About that there is a tip, just create a new boolean string:
**privacy.resistFingerprinting.block_mozAddonManager** and set to **true**
Now the addons works on all Mozilla pages.

**Comment by MikkCZ** [comment]
FYI the behaviour has changes in Nightly 58 and the page action icon is not shown in the address bar if it's not made to appear. So the difference between 57 and 58 will be only that the add-ons page actions will appear in the page actions menu + you can set them to appear only there and not in the address bar at all.
