### ISSUE TITLE
Icon flickering

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/awesome-rss#61]
The rss icon flickers whenever I'm hovering over some links (for example on github). Do you see the same?

**Comment by shgysk8zer0** [comment]
That's particularly strange. Hovering links does nothing to the icon for me that I have seen.

What sort of flickering is this?
- Changing visibility
- Changing opacity
- Changing color
- Other

I'm beginning to think that I will need to implement some sort of logging for issues like this. I can hardly begin to take a guess at what could be causing flickering.

You changed your browser stylesheet, right? Is it possible that such a change might be causing this?

**Comment by Keith94** [comment]
Hi @shgysk8zer0 

I recorded small gif of this behavior. I don't think it's a stylesheet issue but I'll look into it a bit later.

![2017-12-10_12-31-16](https://user-images.githubusercontent.com/5490615/33809437-b986edc8-ddab-11e7-88b2-d24cb531f2c8.gif)

**Comment by shgysk8zer0** [comment]
Let me know if you think of anything. I'll review everything and see if there's any way this would be possible from how it's written.

**Comment by Keith94** [comment]
Oooh I found the culprit. There's an add-on called [URL Tooltip](https://addons.mozilla.org/addon/url-tooltip-we/) and one of its features "Hide status panel" is causing that flickering. Strangely it doesn't happen with any other add-on in the urlbar.

Is there anything we can do?

**Comment by shgysk8zer0** [comment]
It looks like URL Tooltip is triggering a page update for every link hover.
I'm looking into determining the cause of the update.

**Comment by shgysk8zer0** [comment]
After reviewing URL Tooltip WE by downloading and extracting the extension, I think that I've found a likely cause to be the use of `history.replaceState`, which triggers a page update. In order to handle AJAX navigation through `fetch` and `history` state changes, I have to re-scan pages when this occurs, which is what causes the icon flickering.

I have not yet figured out a way of determining the nature of a page update to determine whether or not the re-scan can be skipped. The scan for feeds is really the only way to tell whether or not the icon should be shown, so I do not know if it can be avoided.

Have you reported the issue to UTW? They're triggering a false page update just by hovering over a link.

**Comment by Keith94** [comment]
OK, I've sent the developer an email just now with a link to this issue.

**Comment by Keith94** [comment]
From UTW dev:

>As shgysk8zer0 pointed - problem is with "empty" history.replaceState call. There is no way it can cause any trouble with any sites or scrips, but I haven't thought about other addons. It was most simple hack to hide statusbar I figured, but now I have to dig further into firefox sources to find less harmful way.
Only thing I can suggest for now - disable "hide statusbar" and wait for update. Sadly I cant estimate time needed to find another hack point.
