### ISSUE TITLE
Resetting options clears instead of resets options

### ISSUE THREAD

**Issue by happysurf** [shgysk8zer0/awesome-rss#62]
### Steps to reproduce
1.  Go to https://www.hwupgrade.it/ 
2.  Click on RSS icon;
3.  Go with mouse cursor over the panel;

### Expected behavior
The single RSS must be highlighted;

### Actual behavior
The single RSS are highlighted but with graphic glitch;

### Screenshots and/or logs (see how to open the developer console in your browser)
![glitch](https://user-images.githubusercontent.com/13637587/34006201-cb959a1e-e0fd-11e7-9c0f-81d84820f6b6.png)

**Comment by shgysk8zer0** [comment]
@happysurf Have you customized the style at all? Looks like you have possibly set feeds to be bold and with something not-quite-white as background.

**Comment by happysurf** [comment]
These are my settings:

![options](https://user-images.githubusercontent.com/13637587/34007500-4ab188ea-e102-11e7-8b49-26deb7f806dd.png)

**Comment by happysurf** [comment]
OK, I found the fix, if I set the Popup Background on white (was on black by default) the glitch is gone.

**Comment by shgysk8zer0** [comment]
@happysurf The default background is `#ffffff`.
This might be an issue with resetting preferences though.

**Comment by happysurf** [comment]
> This might be an issue with resetting preferences though.

In fact if you reset the preferences back to black color.

**Comment by xyrolaith** [comment]
Even with version 1.2.2 for me no options are saved at all. After installing the addon the browser-extension-data folder is created but without a default storage.js. I even tried to create one myself but no values are retrieved.

**Comment by shgysk8zer0** [comment]
@xyrolaith I've never looked into extension data like that before, but I can say that there is no `storage.js` for me either, yet storage works just fine. I assume this is because I use `browser.storage.sync` instead of `browser.storage.local`.

Are you having any issues with other add-ons using synced storage? Do you have any logs/errors?

**Comment by xyrolaith** [comment]
@shgysk8zer0 Thank you for the clarification. I checked the storage-sync.sqlite in the profile folder and can change values manually which will actually be used on pages with RSS feeds but the options page always shows the defaults and will not save any changes. Unfortunately I do not see any error messages in the console.

Other add-ons using browser.storage.sync are working fine, e.g. if I change something in HTTPS Everywhere I see the changes in the storage file immediatelly.

**Comment by shgysk8zer0** [comment]
@xyrolaith can you open a separate issue for this? It sounds like you're experiencing an issue with [`browser.storage.sync.set`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set) instead of something with the `<form>` for the extension options. Also, do not want to keep sending out notifications to happysurf for a closed issue.
