### ISSUE TITLE
[Feature request] Add InoReader as Feedly

### ISSUE THREAD

**Issue by ivysrono** [shgysk8zer0/awesome-rss#84]

**Comment by shgysk8zer0** [comment]
TL;DR InoReader doesn't provide this functionality.

Unfortunately, InoReader does not seem to provide a way of subscribing through a URI but only though their API. Nor have I found a means of setting InoReader as an RSS handler in Firefox.

It would be possible to implement all of the authentication, API keys, etc. necessary, it is really more appropriate for a dedicated add-on for InoReader that would also be able to list and possibly view and manage feeds in a sidebar. What they provide to developers is intended for building whole apps rather than just a feature in an add-on.

**Comment by shgysk8zer0** [comment]
If you happen to find a way of opening a URL such as `https://www.inoreader.com/subscribe/?feed=...`, I'd be glad to add this.

**Comment by ivysrono** [comment]
I have found that:`https://www.inoreader.com/?add_feed={RSSURL}`

**Comment by shgysk8zer0** [comment]
@ivysrono Thanks!

I wonder why I wasn't able to find that because I searched for it for a while.
