### ISSUE TITLE
Popup breaks with long feed titles

### ISSUE THREAD

**Issue by quassy** [shgysk8zer0/awesome-rss#93]
### Steps to reproduce
1. Visit a page that has a feed with a very long title, such as the comment feed of [this news article](https://www.ghacks.net/2018/07/25/mozilla-plans-to-remove-rss-feed-reader-and-live-bookmarks-support-from-firefox/).
2. Click the feed button.

### Expected behavior
The text should break and the panel item / button should become taller according to the contents. Alternatively the text should be truncated with an ellipsis.

### Actual behavior
The text breaks but the panel item stays the same height and does not adapt to the longer text. Also a vertical scrollbar appears.

### Screenshots and/or logs (see how to open the developer console in your browser)
![longtitle](https://user-images.githubusercontent.com/369996/43361622-c6ee8998-92d3-11e8-9e92-84cc82150c10.png)

**Comment by happysurf** [comment]
In my case all is OK, your RSS text is too big in my opinion, try Arial 13.

![rss](https://user-images.githubusercontent.com/13637587/43364083-a20dd058-9313-11e8-8706-0ee784579352.png)

**Comment by shgysk8zer0** [comment]
![](https://i.imgur.com/H86VY6g.png)

This with Arial 14. I wonder if it's a settings issue or an OS issue. Also, judging by the screenshot, I'm guessing you have a very large monitor.

I'll add something to truncate text, but the overflow is a separate issue that I'll not be able to easily reproduce due to the screen size & OS I have access to, if that's part of the issue.

@quassy could you try changing padding/margins, keeping font at the same size, and let me know if any of that changes the overflow & scrolling?

**Comment by ssokolow** [comment]
Might I suggest this combination of CSS rules?

```css
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```

Here's the [Relevant MDN Page](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow).

**Comment by quassy** [comment]
> In my case all is OK, your RSS text is too big in my opinion, try Arial 13.

My styling and font settings were default.

> Might I suggest this combination of CSS rules?

The new version works, even though the ellipsis is not shown and the text simply truncated.

**Comment by happysurf** [comment]
> Settings weren't changed. Was using Windows 10 and 1366x768 on 13" for that screenshot.

OK, the problem is the screen resolution in your case but you can fix the problem changing the font size in extension options.
